apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brouter-web.fullname" . }}-config
  labels:
    {{- include "brouter-web.labels" . | nindent 4 }}
data:
  {{- with .Values.config.files }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
